### PR TITLE
CI improvement

### LINKED ISSUE #16: Implement CMake (and CI) infrastructure for unit-testing
- [ ] Add functionality in CMakeLists.txt to run unit-tests
- [ ] Update README.md according to the changes

### PR DESCRIPTION
**Pull request by derzhavin3016**

### CODE REVIEW

**Comment by Bryanskiy** [comment]
Could you add functionality from https://github.com/106-inc/sim2022/issues/16 to this patch?

**Comment by derzhavin3016** [comment]
> Could you add functionality from https://github.com/106-inc/sim2022/issues/16 to this patch?

Ok

**Comment by derzhavin3016** [comment]
Closes #16

**Comment by Tako-San** [comment]
huita

**Comment by derzhavin3016** [comment]
> huita

I think it is offensive....

**Review by Tako-San — APPROVED** [review]
LGTM

**Pull request merged**
